// Small offline question bank — used when no API key is set or the network fails.
// Add your own questions here in the same format.
const RAW = [
  ['anatomy', 'Head & neck', 'A patient cannot abduct the right eye; on looking right there is horizontal diplopia. Which cranial nerve is most likely injured?', ['Oculomotor', 'Trochlear', 'Abducens', 'Facial'], 2, 'Lateral rectus, the only abductor of the eye, is supplied by the abducens nerve (CN VI). Oculomotor supplies most other extraocular muscles; trochlear supplies superior oblique; facial nerve has no extraocular supply.', 'LR6 SO4 — rest by CN III.'],
  ['anatomy', 'Upper limb', 'After a radical mastectomy, a woman shows winging of the scapula when pushing against a wall. Which nerve was injured?', ['Thoracodorsal nerve', 'Long thoracic nerve', 'Axillary nerve', 'Suprascapular nerve'], 1, 'The long thoracic nerve (C5–C7) supplies serratus anterior, which holds the scapula against the chest wall. Its injury, common in axillary surgery, causes medial winging.', 'Serratus anterior palsy = winged scapula.'],
  ['physiology', 'CVS', 'The normal pacemaker of the heart is:', ['AV node', 'SA node', 'Bundle of His', 'Purkinje fibres'], 1, 'The SA node has the fastest intrinsic rate of spontaneous depolarisation (about 60–100/min) and therefore sets the heart rate, overriding slower latent pacemakers.', 'Fastest firing tissue sets the rhythm.'],
  ['physiology', 'Renal', 'The normal glomerular filtration rate in a healthy adult is approximately:', ['60 mL/min', '90 mL/min', '125 mL/min', '180 mL/min'], 2, 'Normal GFR is about 125 mL/min (≈180 L/day). 180 L/day is the daily filtered volume, a common distractor.', 'GFR 125 mL/min = 180 L/day.'],
  ['biochemistry', 'Vitamins & minerals', 'A chronic alcoholic presents with confusion, ophthalmoplegia and ataxia. Deficiency of which vitamin is responsible?', ['Pyridoxine', 'Thiamine', 'Niacin', 'Cobalamin'], 1, 'Wernicke encephalopathy results from thiamine (B1) deficiency. Thiamine should be given before glucose to avoid precipitating it.', 'Give thiamine before glucose.'],
  ['biochemistry', 'Inborn errors of metabolism', 'An infant develops jaundice, vomiting and cataract after starting milk feeds. The most likely deficient enzyme is:', ['Galactokinase', 'Galactose-1-phosphate uridyltransferase', 'Aldolase B', 'Glucose-6-phosphatase'], 1, 'Classic galactosemia is due to GALT deficiency, causing liver dysfunction, vomiting, cataract and E. coli sepsis. Galactokinase deficiency causes cataract only; aldolase B deficiency is hereditary fructose intolerance.', 'Classic galactosemia = GALT; E. coli sepsis risk.'],
  ['pathology', 'Hematology', 'Reed–Sternberg cells are characteristic of:', ['Burkitt lymphoma', 'Hodgkin lymphoma', 'Multiple myeloma', 'Hairy cell leukaemia'], 1, 'Reed–Sternberg cells (CD15+, CD30+) are the neoplastic cells of classical Hodgkin lymphoma.', 'RS cells: CD15 and CD30 positive.'],
  ['pathology', 'Hematology', 'The Philadelphia chromosome t(9;22) is classically associated with:', ['CML', 'CLL', 'AML-M3', 'Burkitt lymphoma'], 0, 't(9;22) creates the BCR-ABL fusion tyrosine kinase in CML, which is the target of imatinib. AML-M3 is t(15;17); Burkitt is t(8;14).', 'BCR-ABL → imatinib.'],
  ['pharmacology', 'Antidotes & toxicology', 'The specific antidote for paracetamol poisoning is:', ['Flumazenil', 'N-acetylcysteine', 'Naloxone', 'Fomepizole'], 1, 'N-acetylcysteine replenishes glutathione and detoxifies NAPQI. Flumazenil is for benzodiazepines, naloxone for opioids, fomepizole for methanol/ethylene glycol.', 'NAC is most effective within 8 hours.'],
  ['pharmacology', 'CVS drugs', 'Heparin overdose is reversed by:', ['Vitamin K', 'Protamine sulfate', 'Fresh frozen plasma', 'Tranexamic acid'], 1, 'Protamine sulfate, a basic protein, binds acidic heparin and neutralises it. Vitamin K reverses warfarin.', 'Heparin → protamine; warfarin → vitamin K.'],
  ['microbiology', 'Bacteriology', 'Weil disease is caused by:', ['Borrelia recurrentis', 'Leptospira interrogans', 'Treponema pallidum', 'Rickettsia prowazekii'], 1, 'Weil disease is the severe icterohaemorrhagic form of leptospirosis, with jaundice, renal failure and haemorrhage, typically after exposure to rat urine–contaminated water.', 'Leptospirosis: rat urine, floods, farmers.'],
  ['microbiology', 'Virology', 'Negri bodies are seen in:', ['Rabies', 'Herpes simplex', 'Cytomegalovirus', 'Measles'], 0, 'Negri bodies are eosinophilic intracytoplasmic inclusions in neurons (hippocampal pyramidal and Purkinje cells) in rabies.', 'Negri bodies: hippocampus and Purkinje cells.'],
  ['fmt', 'Asphyxial deaths', 'Fracture of the hyoid bone is most characteristic of:', ['Hanging', 'Throttling', 'Drowning', 'Smothering'], 1, 'Throttling (manual strangulation) applies direct pressure to the neck and commonly fractures the hyoid bone and thyroid cartilage.', 'Throttling → hyoid fracture.'],
  ['psm', 'Environment & occupational health', 'The minimum free residual chlorine required in drinking water after one hour of contact is:', ['0.1 mg/L', '0.5 mg/L', '1 mg/L', '2 mg/L'], 1, 'For effective disinfection, 0.5 mg/L of free residual chlorine should remain after a contact period of one hour.', '0.5 mg/L after 1 hour.'],
  ['psm', 'Vaccines & immunisation', 'Under India’s Universal Immunisation Programme, the first dose of MR vaccine is given at:', ['6 weeks', '14 weeks', '9–12 months', '16–24 months'], 2, 'MR-1 is given at 9–12 completed months and MR-2 at 16–24 months under the UIP schedule.', 'MR1: 9–12 months; MR2: 16–24 months.'],
  ['medicine', 'Critical care & ECG', 'The first-line drug in anaphylactic shock is:', ['IV hydrocortisone', 'IM adrenaline', 'IV chlorpheniramine', 'Nebulised salbutamol'], 1, 'IM adrenaline 0.5 mg (1:1000) in the anterolateral thigh is first-line. Steroids and antihistamines are adjuncts and do not treat shock or airway oedema acutely.', 'Adrenaline 1:1000, 0.5 mg IM.'],
  ['medicine', 'Endocrinology', 'Kussmaul breathing is a feature of:', ['Metabolic alkalosis', 'Metabolic acidosis', 'Respiratory acidosis', 'Respiratory alkalosis'], 1, 'Deep, rapid Kussmaul respiration is respiratory compensation for metabolic acidosis, classically in diabetic ketoacidosis.', 'DKA → Kussmaul breathing.'],
  ['surgery', 'Hepatobiliary & pancreas', 'Fever with chills, jaundice and right upper quadrant pain suggests:', ['Acute cholecystitis', 'Acute cholangitis', 'Acute pancreatitis', 'Liver abscess'], 1, 'This is Charcot’s triad of acute ascending cholangitis. Adding hypotension and altered sensorium gives Reynolds’ pentad.', 'Charcot triad + shock + confusion = Reynolds pentad.'],
  ['surgery', 'Hernia', 'The most common type of hernia in women is:', ['Femoral', 'Indirect inguinal', 'Direct inguinal', 'Umbilical'], 1, 'Indirect inguinal hernia is the commonest hernia in both sexes. Femoral hernia is more common in women than in men but is still less common than inguinal hernia.', 'Femoral: more in females, but inguinal is still commonest.'],
  ['obg', 'Hypertensive disorders', 'The drug of choice to control seizures in eclampsia is:', ['Phenytoin', 'Diazepam', 'Magnesium sulfate', 'Labetalol'], 2, 'Magnesium sulfate is superior to phenytoin and diazepam for preventing recurrent eclamptic fits. Monitor knee jerk, respiratory rate and urine output; antidote is calcium gluconate.', 'MgSO4 toxicity antidote: calcium gluconate.'],
  ['obg', 'Obstetric haemorrhage', 'The most common site of ectopic pregnancy is:', ['Isthmus', 'Ampulla', 'Interstitial part', 'Ovary'], 1, 'The ampulla is the commonest site. The isthmus tends to rupture earliest; interstitial pregnancy ruptures latest and bleeds most.', 'Ampulla commonest; isthmus ruptures earliest.'],
  ['pediatrics', 'Growth & development', 'A normally developing child can sit without support at about:', ['3 months', '5 months', '8 months', '12 months'], 2, 'Children sit with support around 6 months and without support around 8 months; standing with support is at about 9 months.', 'Sits alone ~8 months; walks alone ~13 months.'],
  ['ent', 'Nose & PNS', 'Little’s area, the common site of epistaxis, is located at:', ['Posterior superior septum', 'Anteroinferior part of the nasal septum', 'Inferior turbinate', 'Roof of the nose'], 1, 'Kiesselbach’s plexus lies in Little’s area on the anteroinferior septum, where several arteries anastomose; it accounts for most anterior bleeds.', 'Kiesselbach: anterior ethmoidal, sphenopalatine, greater palatine, superior labial.'],
  ['ophthalmology', 'Retina', 'Sudden painless loss of vision with a cherry-red spot at the macula suggests:', ['Central retinal vein occlusion', 'Central retinal artery occlusion', 'Retinal detachment', 'Vitreous haemorrhage'], 1, 'In CRAO the ischaemic, opaque retina surrounds the fovea, where the choroidal circulation shows through as a cherry-red spot.', 'CRVO = "blood and thunder" fundus.'],
  ['orthopedics', 'Nerve injuries', 'The nerve most commonly injured in extension-type supracondylar fracture of the humerus is:', ['Radial nerve', 'Ulnar nerve', 'Anterior interosseous nerve', 'Axillary nerve'], 2, 'The anterior interosseous branch of the median nerve is most frequently injured, causing inability to make the "OK" sign. Ulnar nerve injury is more common with flexion-type fractures and iatrogenic pinning.', 'AIN palsy: cannot make OK sign.'],
  ['dermatology', 'Papulosquamous disorders', 'Wickham’s striae are seen in:', ['Psoriasis', 'Lichen planus', 'Pityriasis rosea', 'Pemphigus'], 1, 'Wickham’s striae are fine white lines on the surface of lichen planus papules, due to focal hypergranulosis.', 'Lichen planus: 6 Ps — purple, pruritic, polygonal, planar papules and plaques.'],
  ['psychiatry', 'Substance use', 'The drugs of choice for alcohol withdrawal are:', ['Antipsychotics', 'Benzodiazepines', 'SSRIs', 'Disulfiram'], 1, 'Benzodiazepines (e.g. chlordiazepoxide, or lorazepam in liver disease) prevent withdrawal seizures and delirium tremens. Disulfiram is for maintaining abstinence, not withdrawal.', 'Liver disease → lorazepam/oxazepam.'],
  ['anesthesia', 'Muscle relaxants', 'The drug used to treat malignant hyperthermia is:', ['Dantrolene', 'Neostigmine', 'Sugammadex', 'Baclofen'], 0, 'Dantrolene blocks calcium release from the sarcoplasmic reticulum via the ryanodine receptor (RyR1). Triggers include volatile anaesthetics and succinylcholine.', 'Earliest sign: rise in end-tidal CO2.'],
  ['radiology', 'Neuroimaging', 'The initial investigation of choice for suspected acute subarachnoid haemorrhage is:', ['MRI brain', 'Non-contrast CT head', 'Cerebral angiography', 'Lumbar puncture'], 1, 'Non-contrast CT is fast and highly sensitive in the first hours. If it is negative but suspicion remains, lumbar puncture for xanthochromia is done; angiography locates the aneurysm.', 'Thunderclap headache → NCCT first.'],
  ['pharmacology', 'Chemotherapy - antimicrobials', 'Red-orange discolouration of urine and tears is caused by:', ['Isoniazid', 'Rifampicin', 'Ethambutol', 'Pyrazinamide'], 1, 'Rifampicin causes harmless orange-red discolouration of body fluids and can stain contact lenses. It is also a potent enzyme inducer.', 'Rifampicin: enzyme inducer, orange secretions.'],
];

export const BANK = RAW.map(([subject, topic, stem, options, answer, explanation, pearl], i) => ({
  id: 'bank-' + i, subject, topic, difficulty: 'moderate', stem, options, answer, explanation, pearl, src: 'bank',
}));
